### PR TITLE
Add Regression.Formula to Dump()

### PR DESCRIPTION
**Pull request by TimSimmons**
The first thing I was looking for when I found the package
was the Formula. I ended up having to get the example, run the code
and play with it before I could figure out what I needed. So
I think the Dump() benefits from having the Formula in it, and
I wanted to beef up the README a bit so that future users
see the goodness easier!

### CODE REVIEW

**Comment by dhowden** [comment]
That's great, thanks for the patch.

Just one thing: could you rewrite the commit message to be more succinct?

Cheers

**Comment by TimSimmons** [comment]
Done :+1:

**Comment by dhowden** [comment]
Brilliant, thanks for the patch!

**Comment by TimSimmons** [comment]
You bet! Thanks for the awesome package!

**Pull request merged**
